Graduation2/app/foreground/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField, TextAreaField
from wtforms.validators import DataRequired, Email, EqualTo, ValidationError, Regexp
from app.models import User


class SuggestionForm(FlaskForm):
    name = StringField(
        label="姓名",
        validators=[DataRequired("姓名不能为空！")],
        render_kw={
            "placeholder": "请输入姓名！",
            "class": "form-control",
        }
    )
    email = StringField(
        label="邮箱",
        validators=[DataRequired("邮箱不能为空！"),
                    Email("邮箱格式不正确！")],
        render_kw={
            "placeholder": "请输入邮箱！",
            "type": "email",
            "class": "form-control"
        }
    )
    suggestion = TextAreaField(
        label="意见建议",
        validators=[DataRequired("内容不能为空！")],
        render_kw={
            "placeholder": "请输入内容！",
            "class": "form-control",
            "rows": 7
        }
    )
    submit = SubmitField(
        "发送消息",
        render_kw={
            "class": "form-control",
        }
    )

Graduation2/app/foreground/__init__.py
from flask import Blueprint


foreground = Blueprint("foreground", __name__, url_prefix="/foreground")

from . import views, errors

Graduation2/app/foreground/views.py
from flask import redirect, url_for, flash, render_template, request
from . import foreground
from app.models import Scenic, Area, Collect, Travels, Suggestion
from sqlalchemy import and_
from flask_login import current_user, login_required
from app import db
from app.foreground.forms import SuggestionForm


@foreground.route("/index")
def index():
    area = Area.query.all()
    hot_area = Area.query.filter_by(is_recommended=1).limit(2).all()
    scenic = Scenic.query.filter_by(is_hot=1).all()
    # for v in scenic:
    # print(v.introduction)
    return render_template("foreground/index.html", area=area, hot_area=hot_area, scenic=scenic)


@foreground.route("/search")
def search():
    """搜索功能

       Args:

       Returns:

       Raise:

       """
    page = request.args.get("page", 1, type=int)
    area = Area.query.all()
    area_id = request.args.get("area_id", type=int)
    star = request.args.get("star", type=int)

    if area_id or star:
        filters = and_(Scenic.area_id == area_id, Scenic.star == star)
        page_data = Scenic.query.filter(filters).paginate(page=page, per_page=3)
    else:
        page_data = Scenic.query.paginate(page=page, per_page=3)
    return render_template("foreground/search.html", page_data=page_data, area=area, area_id=area_id, star=star)


@foreground.route("/info/<int:id>")
def info(id=None):
    """详情页

        Args:

        Returns:

        Raise:

        """

    scenic = Scenic.query.get_or_404(int(id))
    user_id = current_user.id if current_user.is_authenticated else None
    if user_id:
        count = Collect.query.filter_by(
            user_id=int(user_id),
            scenic_id=int(id)
        ).count()
    else:
        user_id = 0
        count = 0
    return render_template("foreground/info.html", scenic=scenic, user_id=user_id, count=count)


@foreground.route("/travels/<int:id>/")
def travels(id=None):
    """详情页

    Args:

    Returns:

    Raise:

    """
    travels = Travels.query.get_or_404(int(id))
    return render_template('foreground/travels.html', travels=travels)


@foreground.route("/collect_add")
def collect_add():
    """收藏景区

    Args:

    Returns:

    Raise:

    """
    scenic_id = request.args.get("scenic_id", "")
    user_id = current_user.id
    collect = Collect.query.filter_by(
        user_id=int(user_id),
        scenic_id=int(scenic_id)
    ).count()
    if collect == 1:
        data = dict(ok=0)
    if collect == 0:
        collect = Collect(
            user_id=int(user_id),
            scenic_id=int(scenic_id)
        )
        db.session.add(collect)
        db.session.commit()
        data = dict(ok=1)
    import json
    return json.dumps(data)


@foreground.route("/collect_del")
def collect_del():
    """取消收藏

    Args:

    Returns:

    Raise:

    """
    if request.args.get("collect_id"):
        scenic_id = Collect.query.filter_by(id=request.args.get("collect_id")).first().scenic_id
    else:
        scenic_id = request.args.get("scenic_id")
    user_id = current_user.id
    collect = Collect.query.filter_by(
        user_id=int(user_id),
        scenic_id=int(scenic_id)
    ).first()
    db.session.delete(collect)
    db.session.commit()
    data = dict(ok=1)
    import json
    return json.dumps(data)


@foreground.route("/collect_list")
@login_required
def collect_list():
    # 获取page参数值
    page = request.args.get("page", 1, type=int)
    # 根据user_id筛选Collect表数据
    page_data = Collect.query.filter_by(user_id=current_user.id).order_by(
        Collect.add_time.desc()
    # 使用分页方法
    ).paginate(page=page, per_page=3)
    # 渲染模板
    print(page_data.items)
    return render_template("foreground/collect_list.html", page_data=page_data)


@foreground.route("suggestion", methods=["POST", "GET"])
@login_required
def suggestion():
    form = SuggestionForm()
    if form.validate_on_submit():
        data = form.data
        suggestion = Suggestion(name=data["name"],
                                email=data["email"],
                                suggestion=data["suggestion"])
        db.session.add(suggestion)
        db.session.commit()
        flash("您的建议我们已收到,感谢您的提供!", "ok")
        return redirect(url_for("foreground.suggestion"))
    return render_template("foreground/suggestion_list.html", form=form)

Graduation2/app/templates/foreground/collect_list.html
{% extends "base.html" %}
{% import "common/home_page.html" as pg %}
{% block content %}
<div id="main">
<div id="content">
    <div class="container">
        <div class="tabs_wrapper tabs1_wrapper">
            <div class="tabs tabs2">
                <div class="tabs_content tabs1_content">
                    <div id="tabs-1">
                        <div style="...">
                            全部收藏
                        </div>
                        <div class="row">
                            <div class="col-sm-12">
                                {% if not page_data.items %}
                                    <div class="txt1" style="...">暂时没有收藏景区！</div>
                                {% else %}
                                    <div class="row">
                                        {% for v in page_data.items %}
                                        <div class="col-sm-4">
                                            <div class="thumb4">
                                                <div class="thumbnail clearfix">
                                                    <figure>
                                                        <a href="{{url_for('foreground.info',id=v.scenic.id)}}">
                                                            <img src="{{url_for('static',filename=v.scenic.logo)}}" height="240px" class="">
                                                        </a>
                                                    </figure>
                                                    <div class="caption">
                                                        <div class="txt1">{{v.scenic.title}}</div>
                                                        <div class="txt3 clearfix">
                                                            <div class="left_side">
                                                                <div class="nums">{{v.scenic.address}}</div>
                                                            </div>
                                                            <div class="right_side"><a href="javascript:;" class="collect_cancel btn-default btn1" value={{v.id}}>取消收藏</a></div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        {% endfor %}
                                    </div>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}
{% block scripts %}
{{super()}}
<script src="{{url_for('static',filename='layer/layer.js')}}"></script>
<script>
    $(document).ready(function(){
        $(".collect_cancel").click(function(){ // 触发点击事件
            var id = $(this).attr("value");  // 获取收藏ID
            $.ajax({
                url: "{{url_for('foreground.collect_del')}}",  //提交URL
                type: "GET",  // 提交方式为GET
                data: {collect_id:id},  // 传递参数
                dataType: "json",  // 设置数据类型为json
                success: function(res){  // 操作成功执行语句
                    if (res.ok == 1){
                        layer.msg("取消收藏!", {icon:1, time:1000}, function(){  // 弹出提示信息
                            window.location.reload();  // 重新加载页面
                        });
                    } else {
                        layer.msg("取消收藏失败!", {icon:2, time:2000}); // 弹出提示信息
                    }
                }
            })
        })
    })
</script>
{% endblock %}

Graduation2/app/templates/foreground/index.html
{% extends "base.html" %}

{% block title %}Graduation {% endblock %}

{% block content %}
<!-- 导入幻灯 -->

<div id="front_tabs">
    <div class="container">
        <div calss="tabs_wrapper tabs1_wrapper">
            <div class="tabs tabs1">
                <div class="tabs_tabs tabs1_tabs">
                    <ul>
                        <li class="active flights"><a href="#tabs-1">Flights</a> </li>
                    </ul>
                </div>
                <div class="tabs_content tabs1_content">
                    <div id="tabs-1">
                        <!-- 导入搜索框 -->
                        {% include "foreground/search_box.html" %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="popular_cruises1">
    <div class="container">
        <h2 class="animated">热门景区</h2>
        <br><br>
        <div id="popular_wrapper" class="animated" data-animation="fadeIn" data-animation-delay="300">
            <div id="popular_inner">
                <div id="popular">
                    <div class="carousel-box">
                        <div class="inner">
                            <div class="carousel main">
                                <ul>
                                    {% for v in scenic %}
                                    <li>
                                        <div class="popular">
                                            <div class="popular_inner">
                                                <figure>
                                                    <img src="{{url_for('static',filename=v.logo)}}" alt="" class="img-responsive">
                                                    <div class="over">
                                                        <div class="v1">{{v.title}}<span>{{v.area.name}}</span></div>
                                                        <div class="v2">{{v.introduction.replace(v.introduction[100:],'...')}}</div>
                                                    </div>
                                                </figure>
                                                <div class="caption">
                                                    <div class="txt1"><span>{{v.title}}</span>{{v.area.name}}</div>
                                                    <div class="txt2">{{v.address}}</div>
                                                    <div class="txt3 clearfix">
                                                    <div class="stars1">
                                                            {% for i in range(5) %}
                                                                {% if i < v.star %}
                                                                    <img src="{{url_for('static',filename='star4.PNG')}}" alt="">
                                                                {% else %}
                                                                    <img src="{{url_for('static',filename='star5.PNG')}}" alt="">
                                                                {% endif %}
                                                            {% endfor %}
                                                        </div>
                                                        <div class="right_side"><a href="{{url_for('foreground.info', id=v.id)}}" class="btn-de">查看</a></div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="popular_pagination"></div>
                </div>
            </div>
        </div>
    </div>
</div>


{% for v in hot_area %}
<div id="team1">
    <div class="container">
        <h2 class="animated">{{v.name}}</h2>
        <div class="title1 animated">{{v.introduction}}</div>
        <br>
        <div class="row">
            {% for vv in v.scenic %}
            <div class="col-sm-4">
                <div class="thumb3 animated" data-animation="flipInY" data-animation-delay="300">
                    <div class="thumbnail clearfix">
                        <figure class="">
                            <a href="">
                                <img src="{{url_for('static', filename=vv.logo)}}" alt="" class="img-response">
                                <div class="over">{{vv.title}}</div>
                            </a>
                        </figure>
                        <div class="caption">
                            <div class="txt1">{{vv.title}}</div>
                            <div class="txt2">{{vv.address}}</div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

Graduation2/app/templates/foreground/info.html
{% extends "base.html" %}
{% block content %}
<div>
    <img src="{{url_for('static',filename='info_3.jpg')}}" style="width:100%;height:300px;">
</div>
<div class="breadcrumbs1_wrapper">
    <div class="container">
        <div class="breadcrumbs1"><a href="/">首页</a><span>/</span>景区详情</div>
    </div>
</div>

<!-- 景区内容 -->
<div id="team1">
    <div class="container">
        <h2 class="animated">{{scenic.title}}
            {% if count %}
                <button class="collect-button">已收藏</button>
            {% else %}
                <button class="collect-button">收藏</button>
            {% endif %}
        </h2>
        <div class="title1">{{scenic.content|safe}}</div>
    </div>
</div>
<!-- 游记列表 -->
<div class="container" style="...">
    <h2 class="animated">{{scenic.title}}游记</h2>
    <div class="row">
        {% if not scenic.travels %}
            <div class="title">暂无游记</div>
        {% else %}
        <div class="col=sm-12 animated undefined visible">
            <ul class="ul2" style="...">
                {% for v in scenic.travels %}
                    <li class="form-groupe">
                        <a href="{{url_for('foreground.travels', id=v.id)}}">{{v.title}}</a>
                    </li>
                {% endfor %}
            </ul>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

{% block scripts %}
{{super()}}
<script src="{{url_for('static', filename='layer/layer.js')}}"></script>
<script>
    $(document).ready(function() {
        $(".collect-button").click(function(){
            user_id = {{ user_id }};
            if(!user_id){
                layer.msg("请先登录",{icon:2,time:2000});
                return false;
            }
            var scenic_id = {{scenic.id}};
            $.ajax({
                url:"{{url_for('foreground.collect_add')}}",
                type:"GET",
                data:{scenic_id:scenic_id},
                dataType:"json",
                success:function(res){
                    if(res.ok == 1){
                        layer.msg("收藏成功！",{icon:1,time:2000});
                        $(".collect-button").empty();
                        $(".collect-button").append("已收藏");
                    } else{
                        layer.msg("您已取消收藏", {icon:2,time:2000});
                        $(".collect-button").empty();
                        $(".collect-button").append("收藏");
                        $.ajax({
                        url:"{{url_for('foreground.collect_del')}}",
                        type:"GET",
                        data:{scenic_id:scenic_id},
                        dataType:"json",})
                            }
                }
            })
        })
    })
</script>
{% endblock %}

Graduation2/app/templates/foreground/quit.html
{% extends "base.html" %}

{% block page_content %}
<div class="page-header">
    <h1>拜拜</h1>
</div>
{% endblock %}

Graduation2/app/templates/foreground/search.html
{% extends "base.html" %}
{% import "common/home_page.html" as pg %}
{% block content %}
<div id="main">
<div id="content">
    <div class="container">
        <div class="tabs_wrapper tabs1_wrapper">
            <div class="tabs tabs2">
                <div class="tabs_content tabs1_content">
                    <div id="tabs-1">
                        {% include "foreground/search_box.html" %}
                        <div class="row">
                            <div class="col-sm-12">
                                {% if not page_data.items %}
                                    <div class="txt1" style="padding:20px;color:red">
                                        没有符合条件的景区,请重新查询
                                    </div>
                                {% else %}
                                <div class="row">
                                    {% for v in page_data.items %}
                                    <div class="col-sm-4">
                                        <div class="thumb4">
                                            <div class="thumbnail clearfix">
                                                <figure>
                                                    <img src="{{url_for('static', filename=v.logo)}}" height="200">
                                                </figure>
                                                <div class="caption">
                                                    <div class="txt1">{{v.title}}</div>
                                                    <div class="txt3 clearfix">
                                                        <div class="left_side">
                                                            <div class="nums">{{v.address}}</div>
                                                        </div>
                                                        <div class="right_side"><a href=""></a></div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    {% endfor %}
                                </div>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="page" style="...">
                {{pg.page(page_data, 'foreground.search')}}
        </div>
    </div>
</div>
</div>

{% endblock %}

Graduation2/app/templates/foreground/search_box.html
<form action="/foreground/search" class="form1" methos="GET">
    <div class="row">
        <!-- 按城市查询 -->
        <div class="col-sm-4 col-md-2">
            <div class="select1_wrapper">
                <label>按城市查询：</label>
                <div class="select1_inner">
                    <select name="area_id" class="select2 select" style="...">
                        {% for v in area %}
                            <option value="{{v.id}}" {% if v.id == area.id %} selected {% endif %}>{{v.name}}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
        </div>
        <!-- 按星级查询 -->
        <div class="col-sm-4 col-md-2">
            <div class="select_wrapper">
                <label>按星级查询：</label>
                <div class="select1_inner">
                    <select name="star" class="select2 select" style="...">
                        {% for i in range(1,6) %}
                        <option value="{{i}}"
                            {% if i == stat %} selected {% endif %}
                            >{{i}}星</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
        </div>
        <div class="col-sm-4 col-md-2">
            <div class="submit-row">
                <input type="submit" value="Search"/>
            </div>
        </div>
    </div>
</form>

Graduation2/app/templates/foreground/suggestion_list.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Graduation suggestion{% endblock %}

{% block content %}
{{super()}}

{% endblock %}

{% block page_content %}
<div class="col-md-4">
    {{wtf.quick_form(form)}}
</div>
{% endblock %}

Graduation2/app/templates/foreground/travels.html
{% extends "base.html" %}
{% block content %}
<div>
    <img width=100% height=270px src="{{url_for('static',filename='travels_1.jpg')}}">
</div>


<div class="breadcrumbs1_wrapper">
    <div class="container">
        <div class="breadcrumbs1">
            <a href="/">首页</a>
            <span>/</span>
            <a href="{{url_for('foreground.info',id=travels.scenic_id)}}">景区</a>
            <span>/</span>游记
        </div>
    </div>
</div>

<div id="team1">
    <div class="container">
        <h2 class="animated">{{travels.title}}</h2>
        <div class="title">作者：{{travels.author}} &nbsp&nbsp&nbsp{{travels.add_time}}</div>
        <div class="content">{{travels.content|safe}}</div>
    </div>
</div>
{% endblock %}

Graduation2/app/templates/foreground/轮播.html
{% extends "base.html" %}

{% block page_content %}
<div class="container" >
    <div class="page-header">
        Welcome!
        {% if current_user.is_authenticated %}
            {{current_user.name}}
        {% else %}
            Stranger
        {% endif %}
    </div>
    <div class="container">
        <div class="carousel slide" id="slidershow" data-ride="carousel">
            <ol class="carousel-indicators">
                <li class="active" data-target="#slidershow" data-slide-to="0"></li>
                <li data-target="#slidershow" data-slide-to="1"></li>
                <li data-target="#slidershow" data-slide-to="2"></li>
                <li data-target="#slidershow" data-slide-to="3"></li>
            </ol>
            <div class="carousel-inner">
                <div class="item active">
                    <img src="{{url_for('static', filename='1.jpg')}}" alt="" style="width:100%;height:80%;display:block;"/>
                    <div class="carousel-caption">
                        <h4>标题一</h4>
                        <p>如图一</p>
                    </div>
                </div>
                <div class="item">
                    <img src="{{url_for('static', filename='2.jpg')}}" alt="" style="width:100%;height:80%;display:block;"/>
                    <div class="carousel-caption">
                        <h4>标题二</h4>
                        <p>如图二</p>
                    </div>
                </div>
                <div class="item">
                    <img src="{{url_for('static', filename='3.jpg')}}" alt="" style="width:100%;height:80%;display:block;"/>
                    <div class="carousel-caption">
                        <h4>标题三</h4>
                        <p>如图三</p>
                    </div>
                </div>
                <div class="item">
                    <img src="{{url_for('static', filename='4.jpg')}}" alt="" style="width:100%;height:80%;display:block;"/>
                    <div class="carousel-caption">
                        <h4>标题四</h4>
                        <p>如图四</p>
                    </div>
                </div>
                <a href="#slidershow" data-slide="prev" class="left carousel-control" role="button">
                    <span class="glyphicon glyphicon-chevron-left"></span>
                </a>
                <a href="#slidershow" data-slide="next" class="right carousel-control" role="button">
                    <span class="glyphicon glyphicon-chevron-right"></span>
                </a>
            </div>
        </div>
    </div>
</div>
{% endblock %}
<!--{% block page_content %}-->
<!--<div class="page-header">-->
<!--    Welcome!-->
<!--    {% if current_user.is_authenticated %}-->
<!--        {{current_user.name}}-->
<!--    {% else %}-->
<!--        Stranger-->
<!--    {% endif %}-->
<!--</div>-->
<!--{% endblock %}-->